export enum Attributes {
  PAGE_NAME = 'Page Name',
  DIRECTION = 'Direction',
  SEARCH_ENGINE = 'Search Engine',
  THEME = 'Theme',
  LANGUAGE = 'Language',
  LANGUAGES = 'Languages',
  DATE_RANGE = 'Date Range',
  SOURCE = 'Source',
  SOURCES = 'Sources',
  LISTING_MODE = 'Listing Mode',
  TARGET = 'Target',
  RESOLUTION = 'Screen Resolution',
  POINTS = 'Points',
  TRIGERED_FROM = 'Trigered From',
  TITLE = 'Title',
  LINK = 'Link',
  SOURCE_TAGS = 'Source Tags',
  OCCUPATION = 'Occupation',
  MAX_VISIBLE_CARDS = 'Max Visible Cards',
  DURATION = 'Duration',
  PROVIDER = 'Provider',
  DISPLAY_LAYOUT = 'Display Layout',
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const noop = (..._args: unknown[]) => {}

export const setupAnalytics = noop
export const setupIdentification = noop
export const trackPageView = noop
export const trackPageScroll = noop
export const trackSearchEngineUse = noop
export const trackSearchEngineSelect = noop
export const trackThemeSelect = noop
export const trackLanguageAdd = noop
export const trackLanguageRemove = noop
export const trackSourceAdd = noop
export const trackSourceRemove = noop
export const trackListingModeSelect = noop
export const trackLinkBookmark = noop
export const trackLinkUnBookmark = noop
export const trackMarkAsRead = noop
export const trackLinkOpen = noop
export const trackTabTarget = noop
export const trackCardLanguageSelect = noop
export const trackCardDateRangeSelect = noop
export const trackChangeLogOpen = noop
export const trackOnboardingStart = noop
export const trackOnboardingSkip = noop
export const trackOnboardingFinish = noop
export const trackRssSourceAdd = noop
export const trackPageDrag = noop
export const trackMaxVisibleCardsChange = noop
export const trackDNDEnable = noop
export const trackDNDDisable = noop
export const trackLinkShare = noop
export const trackLinkCopy = noop
export const trackDisplayTypeChange = noop
export const trackFeedScroll = noop
export const identifyUserLanguages = noop
export const identifyUserListingMode = noop
export const identifyUserCards = noop
export const identifyUserTheme = noop
export const identifyUserSearchEngine = noop
export const identifyUserLinksInNewTab = noop
export const identifyUserOccupation = noop
export const identifyUserMaxVisibleCards = noop
export const identifyDisplayLayout = noop
